services:
  flask:
    build: .
    command: >
      /bin/sh -c "sleep 5 && gunicorn --bind 0.0.0.0:80 app:app"
    env_file: .env
    ports:
      - "80:80"
    stop_signal: SIGINT
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data: